VigenereCryptorCourseMVC/Models/ErrorViewModel.cs
namespace VigenereCryptorCourseMVC.Models
{
	public class ErrorViewModel
	{
		public string? RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
	}
}

VigenereCryptorCourseMVC/Models/SingleFileModel.cs
using System.ComponentModel.DataAnnotations;

namespace VigenereCryptorCourseMVC.Models
{
    public class SingleFileModel 
    {
        public string Message { get; set; }
        public bool IsSuccess { get; set; }
        public bool IsResponse { get; set; }
        [Required(ErrorMessage = "Please enter file name")]
        public string FileName { get; set; }
        [Required(ErrorMessage = "Please select file")]
        public IFormFile File { get; set; }
    }
}

VigenereCryptorCourseMVC/Models/VigenereCryptor.cs
namespace VigenereCryptorCourseMVC.Models
{
    public class VigenereCryptor
    {
        public string Text { get; set; } = "пример текста";
        public string Key { get; set; } = "примерключа";
        public string EditedText { get; set; }
        public bool Mode { get; set; } = true;
        public IFormFile? File { get; set; } = null;
        public string? DownloadLink = null;
        public static string alphabet = "абвгдеёжзийклмнопрстуфхцчшщъыьэюя";
    }
}

VigenereCryptorCourseMVC/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using System.Net.Http.Headers;
using VigenereCryptorCourseMVC.Models;

namespace VigenereCryptorCourseMVC.Controllers
{
	public class HomeController : Controller
	{
		private readonly ILogger<HomeController> _logger;

		public HomeController(ILogger<HomeController> logger)
		{
			_logger = logger;
		}

		public IActionResult Index()
		{
			return View("Index", new VigenereCryptor());
		}

		public IActionResult Privacy()
		{
			return View();
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}
	}
}

VigenereCryptorCourseMVC/Controllers/VigenereCryptorController.cs
using Microsoft.AspNetCore.Mvc;
using VigenereCryptorCourseMVC.Models;
using System.IO;
using System.Web;
using System.Net.Http.Headers;
using System.Text;
using Xceed.Words.NET;

namespace VigenereCryptorCourseMVC.Controllers
{
	public class VigenereCryptorController : Controller
	{
        public IActionResult Index(VigenereCryptor model)
        {
            return View("Index", model);
        }

        [HttpPost]
		public IActionResult UseCryptor(VigenereCryptor model, string dlink)
		{
            model.DownloadLink = dlink; // HiddenFor не работал, пришлось изголяться
            try
            {
				model.EditedText = Crypt(model.Text, model.Key, model.Mode);
                if (model.DownloadLink != null) // если было обращение к файлу
                {
                    string[] temp = model.DownloadLink.Split('.');
                    string extension = temp[temp.Length - 1];
                    bool ifDocx = extension.ToLower() == "docx" ? true : false;

                    if (ifDocx)
                    {
                        DocX docx = DocX.Create(model.DownloadLink);
                        docx.InsertParagraph().InsertText(model.EditedText);
                        docx.Save();
                    }
                    else
                    {
                        System.IO.File.WriteAllText(model.DownloadLink, model.EditedText);
                    }
                    // сразу пишем в файл, который клиент возможно захочет скачать
                }
            }
			catch (FormatException ex)
            {
                model.EditedText = ex.Message;
            }
            return View("Index", model);
        }

        [HttpPost]
        public IActionResult Upload(VigenereCryptor model)
        {
            if (model.File == null)
            {
                return View("Index", model);
            }

            var parsedText = new StringBuilder(); // получаем текст
            using (var reader = new StreamReader(model.File.OpenReadStream()))
            {
                while (reader.Peek() >= 0)
                {
                    parsedText.AppendLine(reader.ReadLine());
                }   
            }

            string path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/Files");

            if (!Directory.Exists(path))
            {
                Directory.CreateDirectory(path);
            }

            using (var stream = new FileStream(Path.Combine(path, model.File.FileName), FileMode.Create)) // получаем файл
            {
                model.File.CopyTo(stream);
            }

            string[] temp = model.File.FileName.Split('.');
            string extension = temp[temp.Length - 1];
            bool ifDocx = (extension.ToLower() == "docx" ? true : false);

            string result = "";
            if (ifDocx) 
            {
                var memst = new MemoryStream();
                model.File.CopyTo(memst);
                DocX docx = DocX.Load(Path.Combine(path, model.File.FileName));
                foreach (var paragraph in docx.Paragraphs)
                {
                    result += paragraph.Text;
                }
            }
            else
            {
                result = parsedText.ToString();
            }

            model.DownloadLink = Path.Combine(path, model.File.FileName);
            model.Text = result.ToString();
            model.EditedText = Crypt(model.Text, model.Key, model.Mode);
            return View("Index", model);
        }
        public static string Crypt(string text, string key, bool mode)
        {
            string result = "";

            int keySymbolIndex = 0; // номер символа в ключе, который используется для шифрования текущего символа текста
            for (int i = 0; i < text.Length; i++)
            {
                int keyIndex = VigenereCryptor.alphabet.IndexOf(key[keySymbolIndex]); // сдвиг по символу ключа
                if (keyIndex == -1)
                {
                    throw new FormatException("В ключе обнаружены символы, не входящие в алфавит, на котором производится шифрование.");
                }
                int textIndex = VigenereCryptor.alphabet.IndexOf(text[i]); // сдвиг по символу текста
                if (textIndex == -1) // если символа в алфавите нет, игнорируем его
                {
                    result += text[i];
                    continue;
                }

                int encryptedIndex; // вычисляем индекс символа алфавита, который пойдёт в результат
                if (mode == true)
                {
                    encryptedIndex = (textIndex + keyIndex) % VigenereCryptor.alphabet.Length;
                }
                else
                {
                    encryptedIndex = (textIndex - keyIndex + VigenereCryptor.alphabet.Length) % VigenereCryptor.alphabet.Length; // плюсану ещё длину алфавита, чтобы в минус не улетало
                }

                result += VigenereCryptor.alphabet[encryptedIndex];

                keySymbolIndex++; // обновляем сдвиг по ключу
                if (keySymbolIndex == key.Length)
                {
                    keySymbolIndex -= key.Length;
                }
            }
            return result;
        }
    }
}

VigenereCryptorCourseMVC/Views/Shared/Index.cshtml
@{
    ViewData["Title"] = "Главная";
}
@model VigenereCryptor
<style>
.grid-container 
{
    display: grid;
    grid-template-columns: 1fr 1fr;
}
textarea 
{
  resize: none;
}
</style>

<form asp-action="UseCryptor" asp-controller="VigenereCryptor" method="post" enctype="multipart/form-data">
    @Html.Hidden("dlink", @Model.DownloadLink)
    <div class="grid-container">
        <div class="grid-child purple">
            Оригинальный текст:
            <br />
            @Html.TextAreaFor(a => a.Text, new { @style="width:500px; height:450px" } )
        </div>
        <div class="grid-child green">
            Изменённый текст:
            <br />
            <textarea style="width:500px; height:450px" readonly placeholder="Тут появится шифрограмма">@Model.EditedText</textarea>
        </div>
    </div>

    Ключ:
    <br />
    @Html.TextBoxFor(a => a.Key, new { @style="width:500px" })
    <br />
    <div class="row">
        <div class="col-6 col-sm-2">
            @Html.RadioButtonFor(a => a.Mode, true, new { @checked = "checked" }) 
            Зашифровать
        </div>
        <div class="col-6 col-sm-2">
            @Html.RadioButtonFor(a => a.Mode, false) 
            Расшифровать
        </div>
    </div>
    <br />
    <input id="cryptButton" type="submit" class="btn btn-primary" value="Отправить"/>
</form>
<br />
<form asp-action="Upload" asp-controller="VigenereCryptor" method="post" enctype="multipart/form-data">
    <button type="submit" class="btn btn-success">Загрузить файл</button>
    <input asp-for="File"/>
    <span asp-validation-for="File"></span>
</form>
<br />
@if (Model != null && Model.DownloadLink != null)
{
    <a class="btn btn-success" onclick="DownloadAlert()" href="@Model.DownloadLink">Скачать файл</a>  
}
<br />
<script src="https://code.jquery.com/jquery-3.6.0.js"></script>
<script type="text/javascript">
function DownloadAlert(){
    alert("Это HTTP загрузка, поэтому современные браузеры её блокируют((( Можете скопировать ссылку и вставить в новую вкладку руками");
};
</script>

VigenereCryptorCourseMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - VigenereCryptorCourseMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/VigenereCryptorCourseMVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">VigenereCryptorCourseMVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Главная</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Конфиденциальность</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - VigenereCryptorCourseMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Конфиденциальность</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>